services:
  docs:
    container_name: monorepo-docs
    build:
      dockerfile: ./apps/docs/Dockerfile
      args:
        TURBO_TEAM: <TURBO_TEAM>
        TURBO_TOKEN: <TURBO_TOKEN>
    restart: always
    ports:
      - 3001:3000
    networks:
      - monorepo

  web:
    container_name: monorepo-web
    build:
      dockerfile: ./apps/web/Dockerfile
      args:
        TURBO_TEAM: <TURBO_TEAM>
        TURBO_TOKEN: <TURBO_TOKEN>
    restart: always
    ports:
      - 3000:3000
    networks:
      - monorepo

networks:
  monorepo:
    driver: bridge